### ISSUE TITLE
Error installing mvn

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [MartinKanters/ChocolateyPackages#4]
```
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://repository.apache.org/content/groups/snapshots/org/apache/maven/apache-maven/4.0.0-alpha-6-SNAPSHOT/apache-maven-4.0.0-alpha-6-20230608.134448-58-bin.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
```

The package URL needs to be updated.

**Comment by MartinKanters** [comment]
Hey, belated thanks for reporting! I didn't notice your issue until last week and also haven't noticed that the GitHub workflow wasn't automatically updating choco packages anymore. I'm not using Windows anymore myself, so that doesn't help... It should all be fixed now. Can your perhaps check?
